Designing HTTPCLIENT-1625
=========================
Michael Osipov <michaelo@apache.org>
:tabsize: 4
:toc:
:icons:
:linkcss:
:homepage: http://people.apache.org/~michaelo/issues/HTTPCLIENT-1625/

This documents tracks the design goals of the completele redesign the GSS-based authentication in
HttpClient. Namely, implementation decisions, known issues, awkward stuff, test environments, etc.

Implementation Decisions
------------------------
Implemenation decisions are comprised of several blocks like interface implementations, exception
handling, logging.

Interface Implementations
~~~~~~~~~~~~~~~~~~~~~~~~~
* AuthSchemeBase implements ContextAwareAuthScheme:
* AuthSchemeProvider:
* Credentials
* `UserTokenHandler`: 


Awkward Stuff
-------------
[qanda]
Why does MalformedChallengeException not extend AuthenticationException though it is documented for
authentication purposes?::
	OK: MalformedChallengeException signals syntax violation of some sort presenting the client from
	understanding the challenge whereas AuthenticationException signals inability or unwillingness
	to respond to the challenge. To me these are different type of issues, but I am open to changing
	it in 5.0.
The name of ChallengeState is quite confusing. Where is the state? This is merely a ChallengeHostType:
	OK: We can deprecate it and replace with AuthCounterpartType or some such in 4.5.

Todos
-----

* Update documentation of `DefaultUserTokenHandler`
